# Generated by Django 4.0.3 on 2022-07-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mukellef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('adres', models.TextField()),
                ('tel', models.PositiveBigIntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('mukellef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.mukellef')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('tc', models.PositiveBigIntegerField()),
                ('adres', models.TextField()),
                ('ise_giris', models.DateTimeField()),
                ('isten_cikis', models.DateTimeField()),
                ('mukellef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.mukellef')),
                ('sube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.sube')),
            ],
        ),
    ]
