# Generated by Django 4.0.3 on 2022-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_ozluk_bordro_bordro_personel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateField()),
                ('ok', models.BooleanField(default=False)),
            ],
        ),
    ]
