# Generated by Django 4.0.3 on 2022-07-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_personel_ise_giris_alter_personel_isten_cikis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozluk',
            name='evraklar',
        ),
        migrations.AddField(
            model_name='ozluk',
            name='adli_sicil_kaydi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='fazla_messai_onay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='gecici_gorev_yazisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='gorevlendirme_belgesi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='hijyen_belgesi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='is_sozlesmesi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='istifa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='kimlik_fotokopisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='mezuniyet_belgesi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='saglik_raporu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='sertifikalar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='veskikalık',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ozluk',
            name='yerlesim_yeri_belgesi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutanak',
            name='tarih',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='OzlukEvrak',
        ),
    ]
