# Generated by Django 4.0.3 on 2022-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_mukellef_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mukellef',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
