# Generated by Django 4.0.3 on 2022-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_mukellef_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='ise_giris',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
