# Generated by Django 4.0.3 on 2022-07-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_personel_ise_giris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='adres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
