# Generated by Django 4.0.3 on 2022-07-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_personel_tamamlandi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordro',
            name='bordro',
        ),
        migrations.RemoveField(
            model_name='tutanak',
            name='tutanak',
        ),
    ]
