# Generated by Django 4.0.3 on 2022-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_remove_bordro_bordro_remove_tutanak_tutanak'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutanak',
            name='baslik',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
