# Generated by Django 4.0.3 on 2022-07-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_tutanak_baslik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='tarih',
        ),
    ]
